name: ファイル出力

on: workflow_dispatch

jobs:
  output:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Output
      run: |
        mkdir -p assets/outputs
        cd src
        find ../assets/inputs/ -name *.xlsx -type f -exec sh -c 'python japanese_school_parser.py "$0" "../assets/outputs/$(basename "$0" .xlsx).json"' {} \;

    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        git config --global user.name "GITHUB_ACTOR"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "[自動生成]パース出力"
        git push origin HEAD:${{ github.ref_name }}
